
import './globals.css'
import SubLayout from './subLayout'
import './scss/index.scss'
import React from 'react'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children   }) {
  return  <SubLayout>
    {children} 
  </SubLayout> 
}
